Improvement: Update CODEOWNERS
eclipse-score/score pull request #77
Opened 2024-12-13 11:35 UTC by aschemmel-tech

Issue-ref: see #39

2025-01-07 11:28 UTC, LittleHuba reviewed
Some comments from my side

2025-01-07 11:28 UTC, LittleHuba commented on .github/CODEOWNERS
> +# *                                              @eclipse-score/infrastructure-tooling-community
I don't think the infrastructure-tooling-community should have final say about codeownership.

Imagine somebody introducing a new directory tree. A change on that level should require an approval from somebody high in the project and not only one of the communities.

Proposal: `@eclipse-score/technical-lead` or `@eclipse-score/project-lead`

2025-01-07 11:28 UTC, LittleHuba commented on .github/CODEOWNERS
> +# docs/features/<feature-name>/architecture      @eclipse-score/automotive-score-committers
Missing a rule for `docs/features`.
This would be the relevant rule when somebody wants to introduce a new feature.

2025-01-07 11:28 UTC, LittleHuba commented on .github/CODEOWNERS
> +# docs/pmp/change_management                     @eclipse-score/technical-lead @eclipse-score/process-community
Don't we want the full `docs/pmp` directory under `@eclipse-score/technical-lead @eclipse-score/process-community`
I don't really see anything that would go under that directory owned by anybody else. If it ever comes to that, we can still split it up.

2025-01-07 11:28 UTC, LittleHuba commented on .github/CODEOWNERS
> +# modules/<module_name>/components               @eclipse-score/automotive-score-committers
Here we probably want more fine-granularity in the long run. More or less a team of experts for a specific module.
But for now this should be sufficient.

2025-01-07 11:28 UTC, LittleHuba commented on .github/CODEOWNERS
> +# docs/features/<feature-name>/safety_analysis   @eclipse-score/automotive-score-committers @eclipse-score/safety-manager
Are you aware that putting more than one owner is an `OR` operation? To me this looks like you thought of an `AND` operation here.

2025-01-07 14:03 UTC, AlexanderLanin requested changes

2025-01-07 14:03 UTC, AlexanderLanin commented on .github/CODEOWNERS
> +# docs/pmp/change_management                     @eclipse-score/technical-lead @eclipse-score/process-community
Yeah we can have one rule for `docs/pmp` and specific rules for e.g. security_management which will involve the security-manager.

2025-01-07 14:03 UTC, AlexanderLanin commented on .github/CODEOWNERS
> +# docs/features/<feature-name>/architecture      @eclipse-score/automotive-score-committers
Potentially the same problem for all top level directories, like /docs.

2025-01-07 14:03 UTC, AlexanderLanin commented on .github/CODEOWNERS
> +# docs/concepts                                  @eclipse-score/automotive-score-committers
Generic: directories should start with `/` since we want to address `/docs/concepts` *only* on the root level with this rule.

```suggestion
# /docs/concepts                                  @eclipse-score/automotive-score-committers
```

2025-01-07 14:03 UTC, AlexanderLanin commented on .github/CODEOWNERS
> +# modules/<module_name>/components               @eclipse-score/automotive-score-committers
Those teams are module=repository specific anyway?!

2025-01-23 09:57 UTC, aschemmel-tech commented on .github/CODEOWNERS
> +# *                                              @eclipse-score/infrastructure-tooling-community
I would agree to Alexander's reasoning, I think the tooling team would ask PL or TL if something of introduce new directory tree dimension would happen.

2025-01-23 09:58 UTC, aschemmel-tech commented on .github/CODEOWNERS
> +# .github                                        @eclipse-score/infrastructure-tooling-community
accept

2025-01-23 10:10 UTC, aschemmel-tech commented on .github/CODEOWNERS
> +# docs/concepts                                  @eclipse-score/automotive-score-committers
ok, will change

2025-01-23 10:28 UTC, aschemmel-tech commented on .github/CODEOWNERS
> +# docs/features/<feature-name>/safety_analysis   @eclipse-score/automotive-score-committers @eclipse-score/safety-manager
is this true? in other github projects I work in, this will lead to an "AND" condition on the reviews

2025-01-23 10:31 UTC, masc2023 commented on .github/CODEOWNERS
> +# process                                        @eclipse-score/process-community
Should there not at least another gateing group, e.g. Quality Manager or also Safety and Security Manager?

2025-01-23 10:32 UTC, AlexanderLanin commented on .github/CODEOWNERS
> +# docs/features/<feature-name>/safety_analysis   @eclipse-score/automotive-score-committers @eclipse-score/safety-manager
We had the same discussion some weeks ago in some other context. I also believe it's OR. But people said that they believe it's AND. Documentation says it's OR.

Maybe we need to just try it.

2025-01-23 11:51 UTC, aschemmel-tech commented on .github/CODEOWNERS
> +# docs/features/<feature-name>/architecture      @eclipse-score/automotive-score-committers
ok, will solve

2025-01-23 12:00 UTC, aschemmel-tech commented on .github/CODEOWNERS
> +# docs/pmp/change_management                     @eclipse-score/technical-lead @eclipse-score/process-community
ok, will change

2025-01-23 12:07 UTC, aschemmel-tech commented on .github/CODEOWNERS
> +# modules/<module_name>/components               @eclipse-score/automotive-score-committers
ok, will split up teams

2025-01-23 12:37 UTC, masc2023 commented on .github/CODEOWNERS
> +# process                                        @eclipse-score/process-community
Would not agree, you mention it also above, so is that not a bottleneck then too? And if the person at the being are the same, the they can be part of e.g. safety managers and community too.

2025-01-23 12:59 UTC, AlexanderLanin approved these changes
Looks good enough for me. It is worth a try to start like that.

Before fully activating it (uncommenting):
* describe workarounds in case we misconfigured something here. Who shall be able to merge regardless of CODEOWNERS? That's typically some admin role.
* those teams are currently not meaningfully filled with people. Don't activate any ownership unless the team is actually set up.

2025-01-28 12:15 UTC, LittleHuba commented on .github/CODEOWNERS
> +# /components/*/            @eclipse-score/<module_name>/automotive-score-committers
@nradakovic @ltekieli when you set up the template repository for modules, could you already add this part there in the CODEOWNERS?

We would probably need a readme there that then tells what steps need to be done manually (e.g. adapting the group names,...)

2025-01-28 12:15 UTC, LittleHuba approved these changes

2025-01-28 12:29 UTC, merged